### ISSUE TITLE
please provide setup instructions

### ISSUE THREAD

**Issue by quickstreamingmedia** [Rjtsahu/School-Bus-Tracking#4]
please provide setup instructions

**Comment by quickstreamingmedia** [comment]
python run.py
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from BusTrack import app
  File "/root/School-Bus-Tracking/BusTrack/__init__.py", line 11, in <module>
    from BusTrack.views.admin import admin
  File "/root/School-Bus-Tracking/BusTrack/views/admin.py", line 4, in <module>
    from BusTrack.helpers import SessionHelper, utils
ImportError: No module named helpers


can you please tell me how to run this

**Comment by quickstreamingmedia** [comment]
please provide instructions deploying it in pythoneverywhere

**Comment by Rjtsahu** [comment]
Hi Venkatesh,

First of this is a flask application with some external dependencies (please refer requirements.txt)
it is using sqlite database so need not to configure any database.

To run the server  you have to execute 'run.py' file.

But you  also need to add some config related to credential and sqlite, here is step how to do this:
- create a folder 'instance' in root project directory
- create a file named 'config.py'
- place the following content in it
<code>
SQLALCHEMY_DATABASE_URI ='sqlite:///data.db'
SQLALCHEMY_TRACK_MODIFICATIONS=True

ADMIN_USERNAME='admin'
ADMIN_PASSWORD=b'$2b$12$9b6h3.H0HIknJAf0vTlyg..tM.dHTOvJDCLO48F04DP7o1zO6KA7m'

# bcrypt
BCRYPT_LOG_ROUNDS = 5

</code>
- Now run the server
- check the admin page on localhost:5000/admin with cred(admin,password)

Hope this will help.

**Comment by yashatkare** [comment]
> Hi Venkatesh,
> 
> First of this is a flask application with some external dependencies (please refer requirements.txt)
> it is using sqlite database so need not to configure any database.
> 
> To run the server you have to execute 'run.py' file.
> 
> But you also need to add some config related to credential and sqlite, here is step how to do this:
> 
> * create a folder 'instance' in root project directory
> * create a file named 'config.py'
> * place the following content in it
> 
> ` SQLALCHEMY_DATABASE_URI ='sqlite:///data.db' SQLALCHEMY_TRACK_MODIFICATIONS=True ADMIN_USERNAME='admin' ADMIN_PASSWORD=b'$2b$12$9b6h3.H0HIknJAf0vTlyg..tM.dHTOvJDCLO48F04DP7o1zO6KA7m' BCRYPT_LOG_ROUNDS = 5 ` - Now run the server - check the admin page on localhost:5000/admin with cred(admin,password)
> Hope this will help.

it shows invalid syntax

**Comment by Rjtsahu** [comment]
can u provide futher detail and line of code which is giving error.
