### ISSUE TITLE
can you give me the environment this project is developed ???

### ISSUE THREAD

**Issue by quickstreamingmedia** [Rjtsahu/School-Bus-Tracking#7]
is a flask app or a Django app? confusion cause running in flask has environment login page is not working I guess somehow it worked so I need exact environment it is developed. please providedetails.

as well as default admin login as well

**Comment by Rjtsahu** [comment]
Hi Venkatesh,

First of this is a flask application with some external dependencies (please refer requirements.txt)
it is using sqlite database so need not to configure any database.

To run the server  you have to execute 'run.py' file.

But you  also need to add some config related to credential and sqlite, here is step how to do this:
- create a folder 'instance' in root project directory
- create a file named 'config.py'
- place the following content in it
<code>
SQLALCHEMY_DATABASE_URI ='sqlite:///data.db'
SQLALCHEMY_TRACK_MODIFICATIONS=True

ADMIN_USERNAME='admin'
ADMIN_PASSWORD=b'$2b$12$9b6h3.H0HIknJAf0vTlyg..tM.dHTOvJDCLO48F04DP7o1zO6KA7m'

# bcrypt
BCRYPT_LOG_ROUNDS = 5

</code>
- Now run the server
- check the admin page on localhost:5000/admin with cred(admin,password)

Hope this will help.

**Comment by Princekas** [comment]
i dont understand how to log in

**Comment by Ananthustalin** [comment]
I cant locate the requirements.txt file
